version: "3.9"
services:

  backend:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_EMV_API_TOKEN_FILE: /run/secrets/api_token_key
    ports:
      - "3000:3000"
    secrets:
      - api_token_key
    env_file:
      - ./backend/.env
    restart: unless-stopped

  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cashRegistration
      POSTGRES_USER: cashier
      POSTGRES_PASSWORD_FILE: /run/secrets/password_db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - password_db

secrets:
  password_db:
    file: ./secrets/password_db
  api_token_key:
    file: ./secrets/api_token_key
